#!/usr/bin/env bash
# shellcheck disable=SC2199
# shellcheck disable=SC2086
# shellcheck source=/dev/null
#
# Copyright (C) 2023-02 xealea <xealea@proton.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Function to read user input with a prompt
read_input() {
	read -p "$1: " user_input
	echo "$user_input"
}

# Prompt user for GitHub email and name
github_email=$(read_input "Enter your GitHub email")
github_name=$(read_input "Enter your GitHub name")

# Set up GitHub configuration
git config --global user.email "$github_email"
git config --global user.name "$github_name"

# Generate SSH key
echo "Generating SSH key..."
ssh-keygen -t rsa -b 4096 -C "$github_email"
echo "SSH key generated."

# Copy SSH key to clipboard if xclip is available
if command -v xclip >/dev/null 2>&1; then
	echo "Copying SSH key to clipboard..."
	xclip -sel clip <~/.ssh/id_rsa.pub
	echo "SSH key copied to clipboard."
else
	echo "xclip is not installed. Please manually copy the SSH key to add to your GitHub account."
fi

# Open GitHub settings page if xdg-open is available
if command -v xdg-open >/dev/null 2>&1; then
	echo "Opening GitHub settings page..."
	xdg-open "https://github.com/settings/keys"
	echo "Please add the SSH key to your GitHub account."
else
	echo "xdg-open is not installed. Please manually open the GitHub settings page and add the SSH key."
fi
