ASM_FILES := $(wildcard *.asm)
SRC_FILES := $(ASM_FILES:.asm=)

TASM := tasm
TLINK := tlink

DOSBOX := dosbox

all: $(SRC_FILES)

%: %.asm
	$(TASM) $<
	$(TLINK) /t $*.obj /o $@

run: $(SRC_FILES)
	$(DOSBOX) -c "mount c ." -c "c:" $(SRC_FILES)

clean:
	rm -f *.obj $(SRC_FILES)

.PHONY: all run clean
